fixes the verification of group "admin" which don't exist in debian (and not in ubuntu too, actually), sudo is the correct one
--- a/CommandNotFound/CommandNotFound.py
+++ b/CommandNotFound/CommandNotFound.py
@@ -90,7 +90,7 @@ class CommandNotFound:
             print _("Could not find the database of available applications, "
                     "run update-command-not-found as root to fix this")
         try:
-            self.user_can_sudo = grp.getgrnam("admin")[2] in posix.getgroups()
+            self.user_can_sudo = grp.getgrnam("sudo")[2] in posix.getgroups()
         except KeyError:
             self.user_can_sudo = False
 
